### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by j0e1337** [Ralex91/DiscordGmodServerStatus#2]
`Error: Cannot find module 'gamedig'
Require stack:
- /root/bot/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Client.<anonymous> (/root/bot/index.js:190:19)
    at Client.emit (node:events:513:28)
    at WebSocketManager.triggerClientReady (/root/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:17)
    at WebSocketManager.checkShardsReady (/root/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:367:10)
    at WebSocketShard.<anonymous> (/root/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:189:14)
    at WebSocketShard.emit (node:events:513:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/bot/index.js' ]
}
`

**Comment by Ralex91** [comment]
Did you install the following modules ?
`discord.js v13` and `gamedig`

If they are not installed do the following commands :
- `npm i discord.js@13.10.3`
- `npm i gamedig`

**Comment by j0e1337** [comment]
gamedig woop woop
