### ISSUE TITLE
something error

### ISSUE THREAD

**Issue by RAINighty** [Ralex91/DiscordGmodServerStatus#3]
`$ npm start

> discord-gmod-status@1.0.0 start
> node index

E:\gmodbot\node_modules\discord.js\src\rest\RequestHandler.js:201
        throw new HTTPError(error.message, error.constructor.name, error.status, request);
              ^

HTTPError [FetchError]: request to https://discord.com/api/v9/gateway/bot failed, reason: read ECONNRESET
    at RequestHandler.execute (E:\gmodbot\node_modules\discord.js\src\rest\RequestHandler.js:201:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RequestHandler.push (E:\gmodbot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async WebSocketManager.connect (E:\gmodbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:134:9)
    at async Client.login (E:\gmodbot\node_modules\discord.js\src\client\Client.js:254:7) {
  code: 500,
  method: 'get',
  path: '/gateway/bot',
  requestData: { json: undefined, files: [] }
}

Node.js v18.13.0

`

**Comment by Ralex91** [comment]
Is your bot's token working well?
